name: MasterDeployZipSrc
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Folder
      run: zip -r src.zip src/
    - name: Release to Github
      run: echo "Release"