name: MasterDeployZipSrc
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Folder
      run: zip -r src.zip src/
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated src.zip: ${timestamp}" || exit 0
        git push